[package]
name = "manim_rs"
version = "0.1.0"
authors = ["ykshin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou="0.14"
cgmath = { version = "0.17", features = ["serde"] }
pennereq = "0.3"
